- hosts: ocp
  sudo: True

  tasks:

    - name: "Get variables"
      include_vars:
        file: vault.yml     # contains vault_rhn_username and vault_rhn_password

    - name: "Get secrets"
      include_vars:
        file: variables.yml # contains openshift_subscription_pool


    - name: Force unregister before register
      redhat_subscription:
        state: absent
      ignore_errors: true

    - name: register node with subscription-manager
      redhat_subscription: state=present username="{{ vault_rhn_username }}" password="{{ vault_rhn_password }}" autosubscribe=false
      register: task_result
      until: task_result | succeeded
      retries: 10
      delay: 5

    - name: attach node to subscription pool
      command: subscription-manager attach --pool {{ item }}
      register: task_result
      until: task_result.rc == 0
      retries: 10
      delay: 1
      ignore_errors: no
      with_items: '{{openshift_subscription_pool}}'

    - name: "Add repositories for OpenShift 3.7"
      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-fast-datapath-rpms"

    - name: "Update the system"
      yum:
        name: '*'
        state: latest

    - name: "Install required packages"
      yum: name={{ item }} state=present
      with_items:
       - vim 
       - telnet 
       - wget 
       - git 
       - net-tools 
       - bind-utils 
       - iptables-services 
       - bridge-utils 
       - bash-completion 
       - nfs-utils

    - name: "Nice to have extra packages"
      yum: name={{ item }} state=present
      with_items:
       - emacs-nox 

    - name: "More packages for OpenShift"
      yum: name={{ item }} state=present
      with_items:
         - ansible
         - atomic-openshift-utils 
         - atomic-openshift-excluder 
         - atomic-openshift-docker-excluder

    - name: "Install Docker"
      yum:
        name: docker
        state: present

    - name: "Configure Docker Storage"
      blockinfile: dest=/etc/sysconfig/docker-storage-setup
                   content="DEVS=/dev/vdb
                   VG=docker-vg"

    - name: "Execute Docker Storage Setup"
      shell:  docker-storage-setup;   

    - name: "Enable Docker Service"
      shell:  systemctl enable docker;   

    - name: "Start Docker Service"
      shell:  systemctl start docker;

    - name: "Unexclude openshift packages"
      shell:   atomic-openshift-excluder unexclude;      

    - name: "Unexclude openshift docker packages"
      shell:   atomic-openshift-docker-excluder unexclude;         
