- hosts: jump
  sudo: True

  tasks:

    - name: "Get variables"
      include_vars:
        file: vault.yml     # contains vault_rhn_username and vault_rhn_password

    - name: "Get secrets"
      include_vars:
        file: variables.yml # contains openshift_subscription_pool


    - name: Force unregister before register
      redhat_subscription:
        state: absent
      ignore_errors: true

    - name: register node with subscription-manager
      redhat_subscription: state=present username="{{ vault_rhn_username }}" password="{{ vault_rhn_password }}" autosubscribe=false
      register: task_result
      until: task_result | succeeded
      retries: 10
      delay: 5

    - name: "Disable all the enabled RHSM repositories"
      shell: subscription-manager repos --disable="*"

    - name: attach node to subscription pool
      command: subscription-manager attach --pool {{ item }}
      register: task_result
      until: task_result.rc == 0
      retries: 10
      delay: 1
      ignore_errors: no
      with_items: '{{openshift_subscription_pool}}'

    - name: "Add repositories for OpenShift 3.10"
      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.10-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"

    - name: "Update the system"
      yum:
        name: '*'
        state: latest

    - name: "Ansible and scripts to drive the openshift installation"
      yum: name={{ item }} state=present
      with_items:
       - openshift-ansible
       - ansible

    - name: "Nice to have extra packages"
      yum: name={{ item }} state=present
      with_items:
       - emacs-nox 
