- hosts: all
  sudo: True

  tasks:

    - name: "register this new system"
      shell: sudo subscription-manager register --username 'XXX' --password 'XXX' --force 

    - name: "attach to the pool that includes OpenShift"
      shell: subscription-manager attach --pool=8a85f9833e1404a9013e3cddf95a0599

    - name: "Add repositories for OpenShift 3.6"
      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.6-rpms" --enable="rhel-7-fast-datapath-rpms"

    - name: "Update the system"
      yum:
        name: '*'
        state: latest

    - name: "Install required packages"
      yum: name={{ item }} state=present
      with_items:
       - vim 
       - telnet 
       - wget 
       - git 
       - net-tools 
       - bind-utils 
       - iptables-services 
       - bridge-utils 
       - bash-completion 
       - nfs-utils

    - name: "Nice to have extra packages"
      yum: name={{ item }} state=present
      with_items:
       - emacs-nox 

    - name: "More packages for OpenShift"
      yum: name={{ item }} state=present
      with_items:
         - ansible
         - atomic-openshift-utils 
         - atomic-openshift-excluder 
         - atomic-openshift-docker-excluder

    - name: "Install Docker"
      yum:
        name: docker
        state: present

    - name: "Configure Docker Storage"
      blockinfile: dest=/etc/sysconfig/docker-storage-setup
                   content="DEVS=/dev/vdb
                   VG=docker-vg"

    - name: "Execute Docker Storage Setup"
      shell:  docker-storage-setup;   

    - name: "Enable Docker Service"
      shell:  systemctl enable docker;   

    - name: "Start Docker Service"
      shell:  systemctl start docker;

    - name: "Unexclude openshift packages"
      shell:   atomic-openshift-excluder unexclude;      

    - name: "Unexclude openshift docker packages"
      shell:   atomic-openshift-docker-excluder unexclude;         
